### ISSUE TITLE
Wrong order of exams

### ISSUE THREAD

**Issue by akutzer** [jembie/jExam-Tracker-Discord#3]
see title

**Comment by jembie** [comment]
feel free to make a PR! :)

**Comment by lukasjuhrich** [comment]
Hasn't this been resolved in 86a3bf86e6007bd863930fc0402355ce6b4b3b4e? After that the order in the jExam news entry should be respected, as was the intention of @jembie

**Comment by akutzer** [comment]
JExam adds new exams at the top, so if we crawl the new exams it should send the last entry of the page first...no idea if the code takes care of this already...haven't read a line :^)) just repeated what @jembie said

maybe the title of the issue is wrong...it should be "Order of the exams is reversed when the bot first crawls the side and there are already some results or if multiple exams get added to jexam at the same time"
